export const countryList = [
  {value: '+93', label: '🇦🇫 +93', name: 'Afghanistan', code: 'AF', flag: '🇦🇫'},
  {
    value: '+358',
    label: '🇦🇽 +358',
    name: 'Åland Islands',
    code: 'AX',
    flag: '🇦🇽',
  },
  {value: '+355', label: '🇦🇱 +355', name: 'Albania', code: 'AL', flag: '🇦🇱'},
  {value: '+213', label: '🇩🇿 +213', name: 'Algeria', code: 'DZ', flag: '🇩🇿'},
  {
    value: '+1684',
    label: '🇦🇸 +1684',
    name: 'American Samoa',
    code: 'AS',
    flag: '🇦🇸',
  },
  {value: '+376', label: '🇦🇩 +376', name: 'Andorra', code: 'AD', flag: '🇦🇩'},
  {value: '+244', label: '🇦🇴 +244', name: 'Angola', code: 'AO', flag: '🇦🇴'},
  {value: '+1264', label: '🇦🇮 +1264', name: 'Anguilla', code: 'AI', flag: '🇦🇮'},
  {value: '+672', label: '🇦🇶 +672', name: 'Antarctica', code: 'AQ', flag: '🇦🇶'},
  {
    value: '+1268',
    label: '🇦🇬 +1268',
    name: 'Antigua and Barbuda',
    code: 'AG',
    flag: '🇦🇬',
  },
  {value: '+54', label: '🇦🇷 +54', name: 'Argentina', code: 'AR', flag: '🇦🇷'},
  {value: '+374', label: '🇦🇲 +374', name: 'Armenia', code: 'AM', flag: '🇦🇲'},
  {value: '+297', label: '🇦🇼 +297', name: 'Aruba', code: 'AW', flag: '🇦🇼'},
  {value: '+61', label: '🇦🇺 +61', name: 'Australia', code: 'AU', flag: '🇦🇺'},
  {value: '+43', label: '🇦🇹 +43', name: 'Austria', code: 'AT', flag: '🇦🇹'},
  {value: '+994', label: '🇦🇿 +994', name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿'},
  {value: '+1242', label: '🇧🇸 +1242', name: 'Bahamas', code: 'BS', flag: '🇧🇸'},
  {value: '+973', label: '🇧🇭 +973', name: 'Bahrain', code: 'BH', flag: '🇧🇭'},
  {value: '+880', label: '🇧🇩 +880', name: 'Bangladesh', code: 'BD', flag: '🇧🇩'},
  {value: '+1246', label: '🇧🇧 +1246', name: 'Barbados', code: 'BB', flag: '🇧🇧'},
  {value: '+375', label: '🇧🇾 +375', name: 'Belarus', code: 'BY', flag: '🇧🇾'},
  {value: '+32', label: '🇧🇪 +32', name: 'Belgium', code: 'BE', flag: '🇧🇪'},
  {value: '+501', label: '🇧🇿 +501', name: 'Belize', code: 'BZ', flag: '🇧🇿'},
  {value: '+229', label: '🇧🇯 +229', name: 'Benin', code: 'BJ', flag: '🇧🇯'},
  {value: '+1441', label: '🇧🇲 +1441', name: 'Bermuda', code: 'BM', flag: '🇧🇲'},
  {value: '+975', label: '🇧🇹 +975', name: 'Bhutan', code: 'BT', flag: '🇧🇹'},
  {
    value: '+591',
    label: '🇧🇴 +591',
    name: 'Bolivia, Plurinational State of bolivia',
    code: 'BO',
    flag: '🇧🇴',
  },
  {
    value: '+387',
    label: '🇧🇦 +387',
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    flag: '🇧🇦',
  },
  {value: '+267', label: '🇧🇼 +267', name: 'Botswana', code: 'BW', flag: '🇧🇼'},
  {
    value: '+47',
    label: '🇧🇻 +47',
    name: 'Bouvet Island',
    code: 'BV',
    flag: '🇧🇻',
  },
  {value: '+55', label: '🇧🇷 +55', name: 'Brazil', code: 'BR', flag: '🇧🇷'},
  {
    value: '+246',
    label: '🇮🇴 +246',
    name: 'British Indian Ocean Territory',
    code: 'IO',
    flag: '🇮🇴',
  },
  {
    value: '+673',
    label: '🇧🇳 +673',
    name: 'Brunei Darussalam',
    code: 'BN',
    flag: '🇧🇳',
  },
  {value: '+359', label: '🇧🇬 +359', name: 'Bulgaria', code: 'BG', flag: '🇧🇬'},
  {
    value: '+226',
    label: '🇧🇫 +226',
    name: 'Burkina Faso',
    code: 'BF',
    flag: '🇧🇫',
  },
  {value: '+257', label: '🇧🇮 +257', name: 'Burundi', code: 'BI', flag: '🇧🇮'},
  {value: '+855', label: '🇰🇭 +855', name: 'Cambodia', code: 'KH', flag: '🇰🇭'},
  {value: '+237', label: '🇨🇲 +237', name: 'Cameroon', code: 'CM', flag: '🇨🇲'},
  {value: '+1', label: '🇨🇦 +1', name: 'Canada', code: 'CA', flag: '🇨🇦'},
  {value: '+238', label: '🇨🇻 +238', name: 'Cape Verde', code: 'CV', flag: '🇨🇻'},
  {
    value: '+345',
    label: '🇰🇾 +345',
    name: 'Cayman Islands',
    code: 'KY',
    flag: '🇰🇾',
  },
  {
    value: '+236',
    label: '🇨🇫 +236',
    name: 'Central African Republic',
    code: 'CF',
    flag: '🇨🇫',
  },
  {value: '+235', label: '🇹🇩 +235', name: 'Chad', code: 'TD', flag: '🇹🇩'},
  {value: '+56', label: '🇨🇱 +56', name: 'Chile', code: 'CL', flag: '🇨🇱'},
  {value: '+86', label: '🇨🇳 +86', name: 'China', code: 'CN', flag: '🇨🇳'},
  {
    value: '+61',
    label: '🇨🇽 +61',
    name: 'Christmas Island',
    code: 'CX',
    flag: '🇨🇽',
  },
  {
    value: '+61',
    label: '🇨🇨 +61',
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    flag: '🇨🇨',
  },
  {value: '+57', label: '🇨🇴 +57', name: 'Colombia', code: 'CO', flag: '🇨🇴'},
  {value: '+269', label: '🇰🇲 +269', name: 'Comoros', code: 'KM', flag: '🇰🇲'},
  {value: '+242', label: '🇨🇬 +242', name: 'Congo', code: 'CG', flag: '🇨🇬'},
  {
    value: '+243',
    label: '🇨🇩 +243',
    name: 'Congo, The Democratic Republic of the Congo',
    code: 'CD',
    flag: '🇨🇩',
  },
  {
    value: '+682',
    label: '🇨🇰 +682',
    name: 'Cook Islands',
    code: 'CK',
    flag: '🇨🇰',
  },
  {value: '+506', label: '🇨🇷 +506', name: 'Costa Rica', code: 'CR', flag: '🇨🇷'},
  {
    value: '+225',
    label: '🇨🇮 +225',
    name: "Cote d'Ivoire",
    code: 'CI',
    flag: '🇨🇮',
  },
  {value: '+385', label: '🇭🇷 +385', name: 'Croatia', code: 'HR', flag: '🇭🇷'},
  {value: '+53', label: '🇨🇺 +53', name: 'Cuba', code: 'CU', flag: '🇨🇺'},
  {value: '+357', label: '🇨🇾 +357', name: 'Cyprus', code: 'CY', flag: '🇨🇾'},
  {
    value: '+420',
    label: '🇨🇿 +420',
    name: 'Czech Republic',
    code: 'CZ',
    flag: '🇨🇿',
  },
  {value: '+45', label: '🇩🇰 +45', name: 'Denmark', code: 'DK', flag: '🇩🇰'},
  {value: '+253', label: '🇩🇯 +253', name: 'Djibouti', code: 'DJ', flag: '🇩🇯'},
  {value: '+1767', label: '🇩🇲 +1767', name: 'Dominica', code: 'DM', flag: '🇩🇲'},
  {
    value: '+1849',
    label: '🇩🇴 +1849',
    name: 'Dominican Republic',
    code: 'DO',
    flag: '🇩🇴',
  },
  {value: '+593', label: '🇪🇨 +593', name: 'Ecuador', code: 'EC', flag: '🇪🇨'},
  {value: '+20', label: '🇪🇬 +20', name: 'Egypt', code: 'EG', flag: '🇪🇬'},
  {
    value: '+503',
    label: '🇸🇻 +503',
    name: 'El Salvador',
    code: 'SV',
    flag: '🇸🇻',
  },
  {
    value: '+240',
    label: '🇬🇶 +240',
    name: 'Equatorial Guinea',
    code: 'GQ',
    flag: '🇬🇶',
  },
  {value: '+291', label: '🇪🇷 +291', name: 'Eritrea', code: 'ER', flag: '🇪🇷'},
  {value: '+372', label: '🇪🇪 +372', name: 'Estonia', code: 'EE', flag: '🇪🇪'},
  {value: '+251', label: '🇪🇹 +251', name: 'Ethiopia', code: 'ET', flag: '🇪🇹'},
  {
    value: '+500',
    label: '🇫🇰 +500',
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    flag: '🇫🇰',
  },
  {
    value: '+298',
    label: '🇫🇴 +298',
    name: 'Faroe Islands',
    code: 'FO',
    flag: '🇫🇴',
  },
  {value: '+679', label: '🇫🇯 +679', name: 'Fiji', code: 'FJ', flag: '🇫🇯'},
  {value: '+358', label: '🇫🇮 +358', name: 'Finland', code: 'FI', flag: '🇫🇮'},
  {value: '+33', label: '🇫🇷 +33', name: 'France', code: 'FR', flag: '🇫🇷'},
  {
    value: '+594',
    label: '🇬🇫 +594',
    name: 'French Guiana',
    code: 'GF',
    flag: '🇬🇫',
  },
  {
    value: '+689',
    label: '🇵🇫 +689',
    name: 'French Polynesia',
    code: 'PF',
    flag: '🇵🇫',
  },
  {
    value: '+262',
    label: '🇹🇫 +262',
    name: 'French Southern Territories',
    code: 'TF',
    flag: '🇹🇫',
  },
  {value: '+241', label: '🇬🇦 +241', name: 'Gabon', code: 'GA', flag: '🇬🇦'},
  {value: '+220', label: '🇬🇲 +220', name: 'Gambia', code: 'GM', flag: '🇬🇲'},
  {value: '+995', label: '🇬🇪 +995', name: 'Georgia', code: 'GE', flag: '🇬🇪'},
  {value: '+49', label: '🇩🇪 +49', name: 'Germany', code: 'DE', flag: '🇩🇪'},
  {value: '+233', label: '🇬🇭 +233', name: 'Ghana', code: 'GH', flag: '🇬🇭'},
  {value: '+350', label: '🇬🇮 +350', name: 'Gibraltar', code: 'GI', flag: '🇬🇮'},
  {value: '+30', label: '🇬🇷 +30', name: 'Greece', code: 'GR', flag: '🇬🇷'},
  {value: '+299', label: '🇬🇱 +299', name: 'Greenland', code: 'GL', flag: '🇬🇱'},
  {value: '+1473', label: '🇬🇩 +1473', name: 'Grenada', code: 'GD', flag: '🇬🇩'},
  {value: '+590', label: '🇬🇵 +590', name: 'Guadeloupe', code: 'GP', flag: '🇬🇵'},
  {value: '+1671', label: '🇬🇺 +1671', name: 'Guam', code: 'GU', flag: '🇬🇺'},
  {value: '+502', label: '🇬🇹 +502', name: 'Guatemala', code: 'GT', flag: '🇬🇹'},
  {value: '+44', label: '🇬🇬 +44', name: 'Guernsey', code: 'GG', flag: '🇬🇬'},
  {value: '+224', label: '🇬🇳 +224', name: 'Guinea', code: 'GN', flag: '🇬🇳'},
  {
    value: '+245',
    label: '🇬🇼 +245',
    name: 'Guinea-Bissau',
    code: 'GW',
    flag: '🇬🇼',
  },
  {value: '+592', label: '🇬🇾 +592', name: 'Guyana', code: 'GY', flag: '🇬🇾'},
  {value: '+509', label: '🇭🇹 +509', name: 'Haiti', code: 'HT', flag: '🇭🇹'},
  {
    value: '+672',
    label: '🇭🇲 +672',
    name: 'Heard Island and Mcdonald Islands',
    code: 'HM',
    flag: '🇭🇲',
  },
  {
    value: '+379',
    label: '🇻🇦 +379',
    name: 'Holy See (Vatican City State)',
    code: 'VA',
    flag: '🇻🇦',
  },
  {value: '+504', label: '🇭🇳 +504', name: 'Honduras', code: 'HN', flag: '🇭🇳'},
  {value: '+852', label: '🇭🇰 +852', name: 'Hong Kong', code: 'HK', flag: '🇭🇰'},
  {value: '+36', label: '🇭🇺 +36', name: 'Hungary', code: 'HU', flag: '🇭🇺'},
  {value: '+354', label: '🇮🇸 +354', name: 'Iceland', code: 'IS', flag: '🇮🇸'},
  {value: '+91', label: '🇮🇳 +91', name: 'India', code: 'IN', flag: '🇮🇳'},
  {value: '+62', label: '🇮🇩 +62', name: 'Indonesia', code: 'ID', flag: '🇮🇩'},
  {
    value: '+98',
    label: '🇮🇷 +98',
    name: 'Iran, Islamic Republic of Persian Gulf',
    code: 'IR',
    flag: '🇮🇷',
  },
  {value: '+964', label: '🇮🇶 +964', name: 'Iraq', code: 'IQ', flag: '🇮🇶'},
  {value: '+353', label: '🇮🇪 +353', name: 'Ireland', code: 'IE', flag: '🇮🇪'},
  {value: '+44', label: '🇮🇲 +44', name: 'Isle of Man', code: 'IM', flag: '🇮🇲'},
  {value: '+972', label: '🇮🇱 +972', name: 'Israel', code: 'IL', flag: '🇮🇱'},
  {value: '+39', label: '🇮🇹 +39', name: 'Italy', code: 'IT', flag: '🇮🇹'},
  {value: '+1876', label: '🇯🇲 +1876', name: 'Jamaica', code: 'JM', flag: '🇯🇲'},
  {value: '+81', label: '🇯🇵 +81', name: 'Japan', code: 'JP', flag: '🇯🇵'},
  {value: '+44', label: '🇯🇪 +44', name: 'Jersey', code: 'JE', flag: '🇯🇪'},
  {value: '+962', label: '🇯🇴 +962', name: 'Jordan', code: 'JO', flag: '🇯🇴'},
  {value: '+7', label: '🇰🇿 +7', name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿'},
  {value: '+254', label: '🇰🇪 +254', name: 'Kenya', code: 'KE', flag: '🇰🇪'},
  {value: '+686', label: '🇰🇮 +686', name: 'Kiribati', code: 'KI', flag: '🇰🇮'},
  {
    value: '+850',
    label: '🇰🇵 +850',
    name: "Korea, Democratic People's Republic of Korea",
    code: 'KP',
    flag: '🇰🇵',
  },
  {
    value: '+82',
    label: '🇰🇷 +82',
    name: 'Korea, Republic of South Korea',
    code: 'KR',
    flag: '🇰🇷',
  },
  {value: '+383', label: '🇽🇰 +383', name: 'Kosovo', code: 'XK', flag: '🇽🇰'},
  {value: '+965', label: '🇰🇼 +965', name: 'Kuwait', code: 'KW', flag: '🇰🇼'},
  {value: '+996', label: '🇰🇬 +996', name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬'},
  {value: '+856', label: '🇱🇦 +856', name: 'Laos', code: 'LA', flag: '🇱🇦'},
  {value: '+371', label: '🇱🇻 +371', name: 'Latvia', code: 'LV', flag: '🇱🇻'},
  {value: '+961', label: '🇱🇧 +961', name: 'Lebanon', code: 'LB', flag: '🇱🇧'},
  {value: '+266', label: '🇱🇸 +266', name: 'Lesotho', code: 'LS', flag: '🇱🇸'},
  {value: '+231', label: '🇱🇷 +231', name: 'Liberia', code: 'LR', flag: '🇱🇷'},
  {
    value: '+218',
    label: '🇱🇾 +218',
    name: 'Libyan Arab Jamahiriya',
    code: 'LY',
    flag: '🇱🇾',
  },
  {
    value: '+423',
    label: '🇱🇮 +423',
    name: 'Liechtenstein',
    code: 'LI',
    flag: '🇱🇮',
  },
  {value: '+370', label: '🇱🇹 +370', name: 'Lithuania', code: 'LT', flag: '🇱🇹'},
  {value: '+352', label: '🇱🇺 +352', name: 'Luxembourg', code: 'LU', flag: '🇱🇺'},
  {value: '+853', label: '🇲🇴 +853', name: 'Macao', code: 'MO', flag: '🇲🇴'},
  {value: '+389', label: '🇲🇰 +389', name: 'Macedonia', code: 'MK', flag: '🇲🇰'},
  {value: '+261', label: '🇲🇬 +261', name: 'Madagascar', code: 'MG', flag: '🇲🇬'},
  {value: '+265', label: '🇲🇼 +265', name: 'Malawi', code: 'MW', flag: '🇲🇼'},
  {value: '+60', label: '🇲🇾 +60', name: 'Malaysia', code: 'MY', flag: '🇲🇾'},
  {value: '+960', label: '🇲🇻 +960', name: 'Maldives', code: 'MV', flag: '🇲🇻'},
  {value: '+223', label: '🇲🇱 +223', name: 'Mali', code: 'ML', flag: '🇲🇱'},
  {value: '+356', label: '🇲🇹 +356', name: 'Malta', code: 'MT', flag: '🇲🇹'},
  {
    value: '+692',
    label: '🇲🇭 +692',
    name: 'Marshall Islands',
    code: 'MH',
    flag: '🇲🇭',
  },
  {value: '+596', label: '🇲🇶 +596', name: 'Martinique', code: 'MQ', flag: '🇲🇶'},
  {value: '+222', label: '🇲🇷 +222', name: 'Mauritania', code: 'MR', flag: '🇲🇷'},
  {value: '+230', label: '🇲🇺 +230', name: 'Mauritius', code: 'MU', flag: '🇲🇺'},
  {value: '+262', label: '🇾🇹 +262', name: 'Mayotte', code: 'YT', flag: '🇾🇹'},
  {value: '+52', label: '🇲🇽 +52', name: 'Mexico', code: 'MX', flag: '🇲🇽'},
  {
    value: '+691',
    label: '🇫🇲 +691',
    name: 'Micronesia, Federated States of Micronesia',
    code: 'FM',
    flag: '🇫🇲',
  },
  {value: '+373', label: '🇲🇩 +373', name: 'Moldova', code: 'MD', flag: '🇲🇩'},
  {value: '+377', label: '🇲🇨 +377', name: 'Monaco', code: 'MC', flag: '🇲🇨'},
  {value: '+976', label: '🇲🇳 +976', name: 'Mongolia', code: 'MN', flag: '🇲🇳'},
  {value: '+382', label: '🇲🇪 +382', name: 'Montenegro', code: 'ME', flag: '🇲🇪'},
  {
    value: '+1664',
    label: '🇲🇸 +1664',
    name: 'Montserrat',
    code: 'MS',
    flag: '🇲🇸',
  },
  {value: '+212', label: '🇲🇦 +212', name: 'Morocco', code: 'MA', flag: '🇲🇦'},
  {value: '+258', label: '🇲🇿 +258', name: 'Mozambique', code: 'MZ', flag: '🇲🇿'},
  {value: '+95', label: '🇲🇲 +95', name: 'Myanmar', code: 'MM', flag: '🇲🇲'},
  {value: '+264', label: '🇳🇦 +264', name: 'Namibia', code: 'NA', flag: '🇳🇦'},
  {value: '+674', label: '🇳🇷 +674', name: 'Nauru', code: 'NR', flag: '🇳🇷'},
  {value: '+977', label: '🇳🇵 +977', name: 'Nepal', code: 'NP', flag: '🇳🇵'},
  {value: '+31', label: '🇳🇱 +31', name: 'Netherlands', code: 'NL', flag: '🇳🇱'},
  {
    value: '+599',
    label: ' +599',
    name: 'Netherlands Antilles',
    code: 'AN',
    flag: '',
  },
  {
    value: '+687',
    label: '🇳🇨 +687',
    name: 'New Caledonia',
    code: 'NC',
    flag: '🇳🇨',
  },
  {value: '+64', label: '🇳🇿 +64', name: 'New Zealand', code: 'NZ', flag: '🇳🇿'},
  {value: '+505', label: '🇳🇮 +505', name: 'Nicaragua', code: 'NI', flag: '🇳🇮'},
  {value: '+227', label: '🇳🇪 +227', name: 'Niger', code: 'NE', flag: '🇳🇪'},
  {value: '+234', label: '🇳🇬 +234', name: 'Nigeria', code: 'NG', flag: '🇳🇬'},
  {value: '+683', label: '🇳🇺 +683', name: 'Niue', code: 'NU', flag: '🇳🇺'},
  {
    value: '+672',
    label: '🇳🇫 +672',
    name: 'Norfolk Island',
    code: 'NF',
    flag: '🇳🇫',
  },
  {
    value: '+1670',
    label: '🇲🇵 +1670',
    name: 'Northern Mariana Islands',
    code: 'MP',
    flag: '🇲🇵',
  },
  {value: '+47', label: '🇳🇴 +47', name: 'Norway', code: 'NO', flag: '🇳🇴'},
  {value: '+968', label: '🇴🇲 +968', name: 'Oman', code: 'OM', flag: '🇴🇲'},
  {value: '+92', label: '🇵🇰 +92', name: 'Pakistan', code: 'PK', flag: '🇵🇰'},
  {value: '+680', label: '🇵🇼 +680', name: 'Palau', code: 'PW', flag: '🇵🇼'},
  {
    value: '+970',
    label: '🇵🇸 +970',
    name: 'Palestinian Territory, Occupied',
    code: 'PS',
    flag: '🇵🇸',
  },
  {value: '+507', label: '🇵🇦 +507', name: 'Panama', code: 'PA', flag: '🇵🇦'},
  {
    value: '+675',
    label: '🇵🇬 +675',
    name: 'Papua New Guinea',
    code: 'PG',
    flag: '🇵🇬',
  },
  {value: '+595', label: '🇵🇾 +595', name: 'Paraguay', code: 'PY', flag: '🇵🇾'},
  {value: '+51', label: '🇵🇪 +51', name: 'Peru', code: 'PE', flag: '🇵🇪'},
  {value: '+63', label: '🇵🇭 +63', name: 'Philippines', code: 'PH', flag: '🇵🇭'},
  {value: '+64', label: '🇵🇳 +64', name: 'Pitcairn', code: 'PN', flag: '🇵🇳'},
  {value: '+48', label: '🇵🇱 +48', name: 'Poland', code: 'PL', flag: '🇵🇱'},
  {value: '+351', label: '🇵🇹 +351', name: 'Portugal', code: 'PT', flag: '🇵🇹'},
  {
    value: '+1939',
    label: '🇵🇷 +1939',
    name: 'Puerto Rico',
    code: 'PR',
    flag: '🇵🇷',
  },
  {value: '+974', label: '🇶🇦 +974', name: 'Qatar', code: 'QA', flag: '🇶🇦'},
  {value: '+40', label: '🇷🇴 +40', name: 'Romania', code: 'RO', flag: '🇷🇴'},
  {value: '+7', label: '🇷🇺 +7', name: 'Russia', code: 'RU', flag: '🇷🇺'},
  {value: '+250', label: '🇷🇼 +250', name: 'Rwanda', code: 'RW', flag: '🇷🇼'},
  {value: '+262', label: '🇷🇪 +262', name: 'Reunion', code: 'RE', flag: '🇷🇪'},
  {
    value: '+590',
    label: '🇧🇱 +590',
    name: 'Saint Barthelemy',
    code: 'BL',
    flag: '🇧🇱',
  },
  {
    value: '+290',
    label: '🇸🇭 +290',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    code: 'SH',
    flag: '🇸🇭',
  },
  {
    value: '+1869',
    label: '🇰🇳 +1869',
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    flag: '🇰🇳',
  },
  {
    value: '+1758',
    label: '🇱🇨 +1758',
    name: 'Saint Lucia',
    code: 'LC',
    flag: '🇱🇨',
  },
  {
    value: '+590',
    label: '🇲🇫 +590',
    name: 'Saint Martin',
    code: 'MF',
    flag: '🇲🇫',
  },
  {
    value: '+508',
    label: '🇵🇲 +508',
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    flag: '🇵🇲',
  },
  {
    value: '+1784',
    label: '🇻🇨 +1784',
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    flag: '🇻🇨',
  },
  {value: '+685', label: '🇼🇸 +685', name: 'Samoa', code: 'WS', flag: '🇼🇸'},
  {value: '+378', label: '🇸🇲 +378', name: 'San Marino', code: 'SM', flag: '🇸🇲'},
  {
    value: '+239',
    label: '🇸🇹 +239',
    name: 'Sao Tome and Principe',
    code: 'ST',
    flag: '🇸🇹',
  },
  {
    value: '+966',
    label: '🇸🇦 +966',
    name: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
  },
  {value: '+221', label: '🇸🇳 +221', name: 'Senegal', code: 'SN', flag: '🇸🇳'},
  {value: '+381', label: '🇷🇸 +381', name: 'Serbia', code: 'RS', flag: '🇷🇸'},
  {value: '+248', label: '🇸🇨 +248', name: 'Seychelles', code: 'SC', flag: '🇸🇨'},
  {
    value: '+232',
    label: '🇸🇱 +232',
    name: 'Sierra Leone',
    code: 'SL',
    flag: '🇸🇱',
  },
  {value: '+65', label: '🇸🇬 +65', name: 'Singapore', code: 'SG', flag: '🇸🇬'},
  {value: '+421', label: '🇸🇰 +421', name: 'Slovakia', code: 'SK', flag: '🇸🇰'},
  {value: '+386', label: '🇸🇮 +386', name: 'Slovenia', code: 'SI', flag: '🇸🇮'},
  {
    value: '+677',
    label: '🇸🇧 +677',
    name: 'Solomon Islands',
    code: 'SB',
    flag: '🇸🇧',
  },
  {value: '+252', label: '🇸🇴 +252', name: 'Somalia', code: 'SO', flag: '🇸🇴'},
  {value: '+27', label: '🇿🇦 +27', name: 'South Africa', code: 'ZA', flag: '🇿🇦'},
  {
    value: '+211',
    label: '🇸🇸 +211',
    name: 'South Sudan',
    code: 'SS',
    flag: '🇸🇸',
  },
  {
    value: '+500',
    label: '🇬🇸 +500',
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    flag: '🇬🇸',
  },
  {value: '+34', label: '🇪🇸 +34', name: 'Spain', code: 'ES', flag: '🇪🇸'},
  {value: '+94', label: '🇱🇰 +94', name: 'Sri Lanka', code: 'LK', flag: '🇱🇰'},
  {value: '+249', label: '🇸🇩 +249', name: 'Sudan', code: 'SD', flag: '🇸🇩'},
  {value: '+597', label: '🇸🇷 +597', name: 'Suriname', code: 'SR', flag: '🇸🇷'},
  {
    value: '+47',
    label: '🇸🇯 +47',
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    flag: '🇸🇯',
  },
  {value: '+268', label: '🇸🇿 +268', name: 'Eswatini', code: 'SZ', flag: '🇸🇿'},
  {value: '+46', label: '🇸🇪 +46', name: 'Sweden', code: 'SE', flag: '🇸🇪'},
  {value: '+41', label: '🇨🇭 +41', name: 'Switzerland', code: 'CH', flag: '🇨🇭'},
  {
    value: '+963',
    label: '🇸🇾 +963',
    name: 'Syrian Arab Republic',
    code: 'SY',
    flag: '🇸🇾',
  },
  {value: '+886', label: '🇹🇼 +886', name: 'Taiwan', code: 'TW', flag: '🇹🇼'},
  {value: '+992', label: '🇹🇯 +992', name: 'Tajikistan', code: 'TJ', flag: '🇹🇯'},
  {
    value: '+255',
    label: '🇹🇿 +255',
    name: 'Tanzania, United Republic of Tanzania',
    code: 'TZ',
    flag: '🇹🇿',
  },
  {value: '+66', label: '🇹🇭 +66', name: 'Thailand', code: 'TH', flag: '🇹🇭'},
  {
    value: '+670',
    label: '🇹🇱 +670',
    name: 'Timor-Leste',
    code: 'TL',
    flag: '🇹🇱',
  },
  {value: '+228', label: '🇹🇬 +228', name: 'Togo', code: 'TG', flag: '🇹🇬'},
  {value: '+690', label: '🇹🇰 +690', name: 'Tokelau', code: 'TK', flag: '🇹🇰'},
  {value: '+676', label: '🇹🇴 +676', name: 'Tonga', code: 'TO', flag: '🇹🇴'},
  {
    value: '+1868',
    label: '🇹🇹 +1868',
    name: 'Trinidad and Tobago',
    code: 'TT',
    flag: '🇹🇹',
  },
  {value: '+216', label: '🇹🇳 +216', name: 'Tunisia', code: 'TN', flag: '🇹🇳'},
  {value: '+90', label: '🇹🇷 +90', name: 'Turkey', code: 'TR', flag: '🇹🇷'},
  {
    value: '+993',
    label: '🇹🇲 +993',
    name: 'Turkmenistan',
    code: 'TM',
    flag: '🇹🇲',
  },
  {
    value: '+1649',
    label: '🇹🇨 +1649',
    name: 'Turks and Caicos Islands',
    code: 'TC',
    flag: '🇹🇨',
  },
  {value: '+688', label: '🇹🇻 +688', name: 'Tuvalu', code: 'TV', flag: '🇹🇻'},
  {value: '+256', label: '🇺🇬 +256', name: 'Uganda', code: 'UG', flag: '🇺🇬'},
  {value: '+380', label: '🇺🇦 +380', name: 'Ukraine', code: 'UA', flag: '🇺🇦'},
  {
    value: '+971',
    label: '🇦🇪 +971',
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
  },
  {
    value: '+44',
    label: '🇬🇧 +44',
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
  },
  {value: '+1', label: '🇺🇸 +1', name: 'United States', code: 'US', flag: '🇺🇸'},
  {value: '+598', label: '🇺🇾 +598', name: 'Uruguay', code: 'UY', flag: '🇺🇾'},
  {value: '+998', label: '🇺🇿 +998', name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿'},
  {value: '+678', label: '🇻🇺 +678', name: 'Vanuatu', code: 'VU', flag: '🇻🇺'},
  {
    value: '+58',
    label: '🇻🇪 +58',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    code: 'VE',
    flag: '🇻🇪',
  },
  {value: '+84', label: '🇻🇳 +84', name: 'Vietnam', code: 'VN', flag: '🇻🇳'},
  {
    value: '+1284',
    label: '🇻🇬 +1284',
    name: 'Virgin Islands, British',
    code: 'VG',
    flag: '🇻🇬',
  },
  {
    value: '+1340',
    label: '🇻🇮 +1340',
    name: 'Virgin Islands, U.S.',
    code: 'VI',
    flag: '🇻🇮',
  },
  {
    value: '+681',
    label: '🇼🇫 +681',
    name: 'Wallis and Futuna',
    code: 'WF',
    flag: '🇼🇫',
  },
  {value: '+967', label: '🇾🇪 +967', name: 'Yemen', code: 'YE', flag: '🇾🇪'},
  {value: '+260', label: '🇿🇲 +260', name: 'Zambia', code: 'ZM', flag: '🇿🇲'},
  {value: '+263', label: '🇿🇼 +263', name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼'},
];
